# Generated by Django 6.0.6 on 2026-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='touch_screen',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
