# Generated by Django 6.0.6 on 2026-07-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_touch_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_borad_gpu',
            new_name='on_board_gpu',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
