# Generated by Django 6.0.6 on 2026-07-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_on_borad_gpu_product_on_board_gpu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
