# Generated by Django 6.0.6 on 2026-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_images_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_board_gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='touch_screen',
            field=models.BooleanField(default=False),
        ),
    ]
