# Generated by Django 6.0.6 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_verified_otp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number'], name='accounts_ot_phone_n_8db646_idx'),
        ),
    ]
